# Site
name: "The Code Monks"
title: "The Code Monks"
description: "Tech bytes for Monks by Monks"
logo: 'assets/images/logo3.png'
favicon: 'assets/images/favicon.ico'
baseurl: 
google_analytics: 'UA-171126841-1'
disqus: 'thecodemonks'
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/
email: thecodemonksorg@gmail.com

# Authors
authors:
  sanjay:
    name: Sanjay
    display_name: Spikey Sanju
    image: https://avatars0.githubusercontent.com/u/23400022?s=460&u=6d4ab222b99d07552d80a6c3fd36f47ec1e071c4&v=4
    email: dvlprsanju@gmail.com
    web: https://github.com/spikeysanju
    twitter: https://twitter.com/sanjay_spikey
    description: "A Passionate Android Developer & UI/UX Ninja"
  waseem:
    name: Waseem
    display_name: Waseem Akram    
    image: https://avatars3.githubusercontent.com/u/12982964?s=460&u=85e440ef14bfab99b297d414d57d73d5ff6a6ced&v=4
    email: wowthemesnet@gmail.com
    web: https://n0nu11.tech
    twitter: https://twitter.com/iamwaseem99
    description: "iOS Developer with Cybersecurity skills"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: prism
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : false



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
